all:
  children:
    cloud1:
      hosts:
        server1:
          ansible_host: YOUR_SERVER_IP_OR_HOSTNAME
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/your_private_key
