---
- name: Deploy Cloud-1
  hosts: cloud1
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common]

    - role: docker
      tags: [docker]

    - role: firewall
      tags: [firewall]

    - role: deploy
      tags: [deploy]
